package com.jw.kids.dao;

import com.jw.kids.bean.TClassPackage;
import com.jw.kids.bean.TClassPackageExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TClassPackageDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_package
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    int countByExample(TClassPackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_package
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    int deleteByExample(TClassPackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_package
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    int deleteByPrimaryKey(Long classPackageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_package
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    int insert(TClassPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_package
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    int insertSelective(TClassPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_package
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    List<TClassPackage> selectByExample(TClassPackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_package
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    TClassPackage selectByPrimaryKey(Long classPackageId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_package
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    int updateByExampleSelective(@Param("record") TClassPackage record, @Param("example") TClassPackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_package
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    int updateByExample(@Param("record") TClassPackage record, @Param("example") TClassPackageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_package
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    int updateByPrimaryKeySelective(TClassPackage record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_package
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    int updateByPrimaryKey(TClassPackage record);
}