package com.jw.kids.dao;

import com.jw.kids.bean.TKids;
import com.jw.kids.bean.TKidsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TKidsDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kids
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    int countByExample(TKidsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kids
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    int deleteByExample(TKidsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kids
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    int deleteByPrimaryKey(Long kId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kids
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    int insert(TKids record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kids
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    int insertSelective(TKids record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kids
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    List<TKids> selectByExample(TKidsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kids
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    TKids selectByPrimaryKey(Long kId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kids
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    int updateByExampleSelective(@Param("record") TKids record, @Param("example") TKidsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kids
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    int updateByExample(@Param("record") TKids record, @Param("example") TKidsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kids
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    int updateByPrimaryKeySelective(TKids record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_kids
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    int updateByPrimaryKey(TKids record);
}