package com.jw.shiro.dao;

import com.jw.shiro.bean.TSysPermission;
import com.jw.shiro.bean.TSysPermissionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TSysPermissionDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_permission
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    int countByExample(TSysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_permission
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    int deleteByExample(TSysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_permission
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    int deleteByPrimaryKey(Long permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_permission
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    int insert(TSysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_permission
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    int insertSelective(TSysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_permission
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    List<TSysPermission> selectByExample(TSysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_permission
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    TSysPermission selectByPrimaryKey(Long permissionId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_permission
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") TSysPermission record, @Param("example") TSysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_permission
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    int updateByExample(@Param("record") TSysPermission record, @Param("example") TSysPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_permission
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    int updateByPrimaryKeySelective(TSysPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_permission
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    int updateByPrimaryKey(TSysPermission record);
}