package com.jw.consult.bean;


import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.sql.Timestamp;

public class TKmConsultKeys implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_km_consult_keys.COLM_ID
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    private Long colmId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_km_consult_keys.TMPLT_ID
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    private Long tmpltId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_km_consult_keys.COLM_NM
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    private String colmNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_km_consult_keys.COLM_TYPE_CD
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    private String colmTypeCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_km_consult_keys.COLM_CODE
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    private String colmCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_km_consult_keys.TSVLD_REGEXP
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    private String tsvldRegexp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_km_consult_keys.HINT_CNTT
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    private String hintCntt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_km_consult_keys.REQUIRED_FLAG
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    private Byte requiredFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_km_consult_keys.FLTR_COND_FLAG
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    private Byte fltrCondFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_km_consult_keys.ARGE_SEQNO
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    private Short argeSeqno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_km_consult_keys.COLM_DESC
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    private String colmDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_km_consult_keys.OP_PRSN_ID
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    private String opPrsnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_km_consult_keys.CRT_TIME
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Timestamp crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_km_consult_keys.MODF_TIME
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Timestamp modfTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_keys
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public TKmConsultKeys(Long colmId, Long tmpltId, String colmNm, String colmTypeCd, String colmCode, String tsvldRegexp, String hintCntt, Byte requiredFlag, Byte fltrCondFlag, Short argeSeqno, String colmDesc, String opPrsnId, Timestamp crtTime, Timestamp modfTime) {
        this.colmId = colmId;
        this.tmpltId = tmpltId;
        this.colmNm = colmNm;
        this.colmTypeCd = colmTypeCd;
        this.colmCode = colmCode;
        this.tsvldRegexp = tsvldRegexp;
        this.hintCntt = hintCntt;
        this.requiredFlag = requiredFlag;
        this.fltrCondFlag = fltrCondFlag;
        this.argeSeqno = argeSeqno;
        this.colmDesc = colmDesc;
        this.opPrsnId = opPrsnId;
        this.crtTime = crtTime;
        this.modfTime = modfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_keys
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public TKmConsultKeys() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_km_consult_keys.COLM_ID
     *
     * @return the value of t_km_consult_keys.COLM_ID
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public Long getColmId() {
        return colmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_km_consult_keys.COLM_ID
     *
     * @param colmId the value for t_km_consult_keys.COLM_ID
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void setColmId(Long colmId) {
        this.colmId = colmId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_km_consult_keys.TMPLT_ID
     *
     * @return the value of t_km_consult_keys.TMPLT_ID
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public Long getTmpltId() {
        return tmpltId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_km_consult_keys.TMPLT_ID
     *
     * @param tmpltId the value for t_km_consult_keys.TMPLT_ID
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void setTmpltId(Long tmpltId) {
        this.tmpltId = tmpltId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_km_consult_keys.COLM_NM
     *
     * @return the value of t_km_consult_keys.COLM_NM
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public String getColmNm() {
        return colmNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_km_consult_keys.COLM_NM
     *
     * @param colmNm the value for t_km_consult_keys.COLM_NM
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void setColmNm(String colmNm) {
        this.colmNm = colmNm == null ? null : colmNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_km_consult_keys.COLM_TYPE_CD
     *
     * @return the value of t_km_consult_keys.COLM_TYPE_CD
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public String getColmTypeCd() {
        return colmTypeCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_km_consult_keys.COLM_TYPE_CD
     *
     * @param colmTypeCd the value for t_km_consult_keys.COLM_TYPE_CD
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void setColmTypeCd(String colmTypeCd) {
        this.colmTypeCd = colmTypeCd == null ? null : colmTypeCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_km_consult_keys.COLM_CODE
     *
     * @return the value of t_km_consult_keys.COLM_CODE
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public String getColmCode() {
        return colmCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_km_consult_keys.COLM_CODE
     *
     * @param colmCode the value for t_km_consult_keys.COLM_CODE
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void setColmCode(String colmCode) {
        this.colmCode = colmCode == null ? null : colmCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_km_consult_keys.TSVLD_REGEXP
     *
     * @return the value of t_km_consult_keys.TSVLD_REGEXP
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public String getTsvldRegexp() {
        return tsvldRegexp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_km_consult_keys.TSVLD_REGEXP
     *
     * @param tsvldRegexp the value for t_km_consult_keys.TSVLD_REGEXP
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void setTsvldRegexp(String tsvldRegexp) {
        this.tsvldRegexp = tsvldRegexp == null ? null : tsvldRegexp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_km_consult_keys.HINT_CNTT
     *
     * @return the value of t_km_consult_keys.HINT_CNTT
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public String getHintCntt() {
        return hintCntt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_km_consult_keys.HINT_CNTT
     *
     * @param hintCntt the value for t_km_consult_keys.HINT_CNTT
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void setHintCntt(String hintCntt) {
        this.hintCntt = hintCntt == null ? null : hintCntt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_km_consult_keys.REQUIRED_FLAG
     *
     * @return the value of t_km_consult_keys.REQUIRED_FLAG
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public Byte getRequiredFlag() {
        return requiredFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_km_consult_keys.REQUIRED_FLAG
     *
     * @param requiredFlag the value for t_km_consult_keys.REQUIRED_FLAG
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void setRequiredFlag(Byte requiredFlag) {
        this.requiredFlag = requiredFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_km_consult_keys.FLTR_COND_FLAG
     *
     * @return the value of t_km_consult_keys.FLTR_COND_FLAG
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public Byte getFltrCondFlag() {
        return fltrCondFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_km_consult_keys.FLTR_COND_FLAG
     *
     * @param fltrCondFlag the value for t_km_consult_keys.FLTR_COND_FLAG
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void setFltrCondFlag(Byte fltrCondFlag) {
        this.fltrCondFlag = fltrCondFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_km_consult_keys.ARGE_SEQNO
     *
     * @return the value of t_km_consult_keys.ARGE_SEQNO
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public Short getArgeSeqno() {
        return argeSeqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_km_consult_keys.ARGE_SEQNO
     *
     * @param argeSeqno the value for t_km_consult_keys.ARGE_SEQNO
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void setArgeSeqno(Short argeSeqno) {
        this.argeSeqno = argeSeqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_km_consult_keys.COLM_DESC
     *
     * @return the value of t_km_consult_keys.COLM_DESC
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public String getColmDesc() {
        return colmDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_km_consult_keys.COLM_DESC
     *
     * @param colmDesc the value for t_km_consult_keys.COLM_DESC
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void setColmDesc(String colmDesc) {
        this.colmDesc = colmDesc == null ? null : colmDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_km_consult_keys.OP_PRSN_ID
     *
     * @return the value of t_km_consult_keys.OP_PRSN_ID
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public String getOpPrsnId() {
        return opPrsnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_km_consult_keys.OP_PRSN_ID
     *
     * @param opPrsnId the value for t_km_consult_keys.OP_PRSN_ID
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void setOpPrsnId(String opPrsnId) {
        this.opPrsnId = opPrsnId == null ? null : opPrsnId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_km_consult_keys.CRT_TIME
     *
     * @return the value of t_km_consult_keys.CRT_TIME
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public Timestamp getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_km_consult_keys.CRT_TIME
     *
     * @param crtTime the value for t_km_consult_keys.CRT_TIME
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void setCrtTime(Timestamp crtTime) {

        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_km_consult_keys.MODF_TIME
     *
     * @return the value of t_km_consult_keys.MODF_TIME
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public Timestamp getModfTime() {
        return modfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_km_consult_keys.MODF_TIME
     *
     * @param modfTime the value for t_km_consult_keys.MODF_TIME
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void setModfTime(Timestamp modfTime) {
        this.modfTime = modfTime;
    }
}