package com.jw.consult.bean;


import com.fasterxml.jackson.annotation.JsonFormat;

import java.io.Serializable;
import java.sql.Timestamp;

public class TKmConsultRowsXxx implements Serializable {

    private String tabNm;

    public void setTabNm(String tabNm) {
        this.tabNm = tabNm;
    }

    public String getTabNm() {
        return tabNm;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_km_consult_rows_xxx.REC_ID
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    private Long recId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_km_consult_rows_xxx.CNSL_ID
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    private Long cnslId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_km_consult_rows_xxx.ARGE_SEQNO
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    private Integer argeSeqno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_km_consult_rows_xxx.OP_PRSN_ID
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    private String opPrsnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_km_consult_rows_xxx.CRT_TIME
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Timestamp crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_km_consult_rows_xxx.MODF_TIME
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+8")
    private Timestamp modfTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_km_consult_rows_xxx.RMK
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    private String rmk;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_km_consult_rows_xxx.TENANT_ID
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    private String tenantId;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_rows_xxx
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public TKmConsultRowsXxx(Long recId, Long cnslId, Integer argeSeqno, String opPrsnId, Timestamp crtTime, Timestamp modfTime, String rmk, String tenantId) {
        this.recId = recId;
        this.cnslId = cnslId;
        this.argeSeqno = argeSeqno;
        this.opPrsnId = opPrsnId;
        this.crtTime = crtTime;
        this.modfTime = modfTime;
        this.rmk = rmk;
        this.tenantId = tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_rows_xxx
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public TKmConsultRowsXxx() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_km_consult_rows_xxx.REC_ID
     *
     * @return the value of t_km_consult_rows_xxx.REC_ID
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public Long getRecId() {
        return recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_km_consult_rows_xxx.REC_ID
     *
     * @param recId the value for t_km_consult_rows_xxx.REC_ID
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void setRecId(Long recId) {
        this.recId = recId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_km_consult_rows_xxx.CNSL_ID
     *
     * @return the value of t_km_consult_rows_xxx.CNSL_ID
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public Long getCnslId() {
        return cnslId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_km_consult_rows_xxx.CNSL_ID
     *
     * @param cnslId the value for t_km_consult_rows_xxx.CNSL_ID
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void setCnslId(Long cnslId) {
        this.cnslId = cnslId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_km_consult_rows_xxx.ARGE_SEQNO
     *
     * @return the value of t_km_consult_rows_xxx.ARGE_SEQNO
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public Integer getArgeSeqno() {
        return argeSeqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_km_consult_rows_xxx.ARGE_SEQNO
     *
     * @param argeSeqno the value for t_km_consult_rows_xxx.ARGE_SEQNO
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void setArgeSeqno(Integer argeSeqno) {
        this.argeSeqno = argeSeqno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_km_consult_rows_xxx.OP_PRSN_ID
     *
     * @return the value of t_km_consult_rows_xxx.OP_PRSN_ID
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public String getOpPrsnId() {
        return opPrsnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_km_consult_rows_xxx.OP_PRSN_ID
     *
     * @param opPrsnId the value for t_km_consult_rows_xxx.OP_PRSN_ID
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void setOpPrsnId(String opPrsnId) {
        this.opPrsnId = opPrsnId == null ? null : opPrsnId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_km_consult_rows_xxx.CRT_TIME
     *
     * @return the value of t_km_consult_rows_xxx.CRT_TIME
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public Timestamp getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_km_consult_rows_xxx.CRT_TIME
     *
     * @param crtTime the value for t_km_consult_rows_xxx.CRT_TIME
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void setCrtTime(Timestamp crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_km_consult_rows_xxx.MODF_TIME
     *
     * @return the value of t_km_consult_rows_xxx.MODF_TIME
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public Timestamp getModfTime() {
        return modfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_km_consult_rows_xxx.MODF_TIME
     *
     * @param modfTime the value for t_km_consult_rows_xxx.MODF_TIME
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void setModfTime(Timestamp modfTime) {
        this.modfTime = modfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_km_consult_rows_xxx.RMK
     *
     * @return the value of t_km_consult_rows_xxx.RMK
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public String getRmk() {
        return rmk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_km_consult_rows_xxx.RMK
     *
     * @param rmk the value for t_km_consult_rows_xxx.RMK
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void setRmk(String rmk) {
        this.rmk = rmk == null ? null : rmk.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_km_consult_rows_xxx.TENANT_ID
     *
     * @return the value of t_km_consult_rows_xxx.TENANT_ID
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public String getTenantId() {
        return tenantId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_km_consult_rows_xxx.TENANT_ID
     *
     * @param tenantId the value for t_km_consult_rows_xxx.TENANT_ID
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void setTenantId(String tenantId) {
        this.tenantId = tenantId == null ? null : tenantId.trim();
    }
}