package com.jw.consult.bean;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

public class TKmConsultKeysExample {

    //add by jw 增加分页功能
    private int startRow;
    private int pageSize;

    public int getStartRow() {
        return startRow;
    }

    public void setStartRow(int startRow) {
        this.startRow = startRow;
    }

    public int getPageSize() {
        return pageSize;
    }

    public void setPageSize(int pageSize) {
        this.pageSize = pageSize;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_km_consult_keys
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_km_consult_keys
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_km_consult_keys
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_keys
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public TKmConsultKeysExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_keys
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_keys
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_keys
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_keys
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_keys
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_keys
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_keys
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_keys
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_keys
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_keys
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_km_consult_keys
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andColmIdIsNull() {
            addCriterion("COLM_ID is null");
            return (Criteria) this;
        }

        public Criteria andColmIdIsNotNull() {
            addCriterion("COLM_ID is not null");
            return (Criteria) this;
        }

        public Criteria andColmIdEqualTo(Long value) {
            addCriterion("COLM_ID =", value, "colmId");
            return (Criteria) this;
        }

        public Criteria andColmIdNotEqualTo(Long value) {
            addCriterion("COLM_ID <>", value, "colmId");
            return (Criteria) this;
        }

        public Criteria andColmIdGreaterThan(Long value) {
            addCriterion("COLM_ID >", value, "colmId");
            return (Criteria) this;
        }

        public Criteria andColmIdGreaterThanOrEqualTo(Long value) {
            addCriterion("COLM_ID >=", value, "colmId");
            return (Criteria) this;
        }

        public Criteria andColmIdLessThan(Long value) {
            addCriterion("COLM_ID <", value, "colmId");
            return (Criteria) this;
        }

        public Criteria andColmIdLessThanOrEqualTo(Long value) {
            addCriterion("COLM_ID <=", value, "colmId");
            return (Criteria) this;
        }

        public Criteria andColmIdIn(List<Long> values) {
            addCriterion("COLM_ID in", values, "colmId");
            return (Criteria) this;
        }

        public Criteria andColmIdNotIn(List<Long> values) {
            addCriterion("COLM_ID not in", values, "colmId");
            return (Criteria) this;
        }

        public Criteria andColmIdBetween(Long value1, Long value2) {
            addCriterion("COLM_ID between", value1, value2, "colmId");
            return (Criteria) this;
        }

        public Criteria andColmIdNotBetween(Long value1, Long value2) {
            addCriterion("COLM_ID not between", value1, value2, "colmId");
            return (Criteria) this;
        }

        public Criteria andTmpltIdIsNull() {
            addCriterion("TMPLT_ID is null");
            return (Criteria) this;
        }

        public Criteria andTmpltIdIsNotNull() {
            addCriterion("TMPLT_ID is not null");
            return (Criteria) this;
        }

        public Criteria andTmpltIdEqualTo(Long value) {
            addCriterion("TMPLT_ID =", value, "tmpltId");
            return (Criteria) this;
        }

        public Criteria andTmpltIdNotEqualTo(Long value) {
            addCriterion("TMPLT_ID <>", value, "tmpltId");
            return (Criteria) this;
        }

        public Criteria andTmpltIdGreaterThan(Long value) {
            addCriterion("TMPLT_ID >", value, "tmpltId");
            return (Criteria) this;
        }

        public Criteria andTmpltIdGreaterThanOrEqualTo(Long value) {
            addCriterion("TMPLT_ID >=", value, "tmpltId");
            return (Criteria) this;
        }

        public Criteria andTmpltIdLessThan(Long value) {
            addCriterion("TMPLT_ID <", value, "tmpltId");
            return (Criteria) this;
        }

        public Criteria andTmpltIdLessThanOrEqualTo(Long value) {
            addCriterion("TMPLT_ID <=", value, "tmpltId");
            return (Criteria) this;
        }

        public Criteria andTmpltIdIn(List<Long> values) {
            addCriterion("TMPLT_ID in", values, "tmpltId");
            return (Criteria) this;
        }

        public Criteria andTmpltIdNotIn(List<Long> values) {
            addCriterion("TMPLT_ID not in", values, "tmpltId");
            return (Criteria) this;
        }

        public Criteria andTmpltIdBetween(Long value1, Long value2) {
            addCriterion("TMPLT_ID between", value1, value2, "tmpltId");
            return (Criteria) this;
        }

        public Criteria andTmpltIdNotBetween(Long value1, Long value2) {
            addCriterion("TMPLT_ID not between", value1, value2, "tmpltId");
            return (Criteria) this;
        }

        public Criteria andColmNmIsNull() {
            addCriterion("COLM_NM is null");
            return (Criteria) this;
        }

        public Criteria andColmNmIsNotNull() {
            addCriterion("COLM_NM is not null");
            return (Criteria) this;
        }

        public Criteria andColmNmEqualTo(String value) {
            addCriterion("COLM_NM =", value, "colmNm");
            return (Criteria) this;
        }

        public Criteria andColmNmNotEqualTo(String value) {
            addCriterion("COLM_NM <>", value, "colmNm");
            return (Criteria) this;
        }

        public Criteria andColmNmGreaterThan(String value) {
            addCriterion("COLM_NM >", value, "colmNm");
            return (Criteria) this;
        }

        public Criteria andColmNmGreaterThanOrEqualTo(String value) {
            addCriterion("COLM_NM >=", value, "colmNm");
            return (Criteria) this;
        }

        public Criteria andColmNmLessThan(String value) {
            addCriterion("COLM_NM <", value, "colmNm");
            return (Criteria) this;
        }

        public Criteria andColmNmLessThanOrEqualTo(String value) {
            addCriterion("COLM_NM <=", value, "colmNm");
            return (Criteria) this;
        }

        public Criteria andColmNmLike(String value) {
            addCriterion("COLM_NM like", value, "colmNm");
            return (Criteria) this;
        }

        public Criteria andColmNmNotLike(String value) {
            addCriterion("COLM_NM not like", value, "colmNm");
            return (Criteria) this;
        }

        public Criteria andColmNmIn(List<String> values) {
            addCriterion("COLM_NM in", values, "colmNm");
            return (Criteria) this;
        }

        public Criteria andColmNmNotIn(List<String> values) {
            addCriterion("COLM_NM not in", values, "colmNm");
            return (Criteria) this;
        }

        public Criteria andColmNmBetween(String value1, String value2) {
            addCriterion("COLM_NM between", value1, value2, "colmNm");
            return (Criteria) this;
        }

        public Criteria andColmNmNotBetween(String value1, String value2) {
            addCriterion("COLM_NM not between", value1, value2, "colmNm");
            return (Criteria) this;
        }

        public Criteria andColmTypeCdIsNull() {
            addCriterion("COLM_TYPE_CD is null");
            return (Criteria) this;
        }

        public Criteria andColmTypeCdIsNotNull() {
            addCriterion("COLM_TYPE_CD is not null");
            return (Criteria) this;
        }

        public Criteria andColmTypeCdEqualTo(String value) {
            addCriterion("COLM_TYPE_CD =", value, "colmTypeCd");
            return (Criteria) this;
        }

        public Criteria andColmTypeCdNotEqualTo(String value) {
            addCriterion("COLM_TYPE_CD <>", value, "colmTypeCd");
            return (Criteria) this;
        }

        public Criteria andColmTypeCdGreaterThan(String value) {
            addCriterion("COLM_TYPE_CD >", value, "colmTypeCd");
            return (Criteria) this;
        }

        public Criteria andColmTypeCdGreaterThanOrEqualTo(String value) {
            addCriterion("COLM_TYPE_CD >=", value, "colmTypeCd");
            return (Criteria) this;
        }

        public Criteria andColmTypeCdLessThan(String value) {
            addCriterion("COLM_TYPE_CD <", value, "colmTypeCd");
            return (Criteria) this;
        }

        public Criteria andColmTypeCdLessThanOrEqualTo(String value) {
            addCriterion("COLM_TYPE_CD <=", value, "colmTypeCd");
            return (Criteria) this;
        }

        public Criteria andColmTypeCdLike(String value) {
            addCriterion("COLM_TYPE_CD like", value, "colmTypeCd");
            return (Criteria) this;
        }

        public Criteria andColmTypeCdNotLike(String value) {
            addCriterion("COLM_TYPE_CD not like", value, "colmTypeCd");
            return (Criteria) this;
        }

        public Criteria andColmTypeCdIn(List<String> values) {
            addCriterion("COLM_TYPE_CD in", values, "colmTypeCd");
            return (Criteria) this;
        }

        public Criteria andColmTypeCdNotIn(List<String> values) {
            addCriterion("COLM_TYPE_CD not in", values, "colmTypeCd");
            return (Criteria) this;
        }

        public Criteria andColmTypeCdBetween(String value1, String value2) {
            addCriterion("COLM_TYPE_CD between", value1, value2, "colmTypeCd");
            return (Criteria) this;
        }

        public Criteria andColmTypeCdNotBetween(String value1, String value2) {
            addCriterion("COLM_TYPE_CD not between", value1, value2, "colmTypeCd");
            return (Criteria) this;
        }

        public Criteria andColmCodeIsNull() {
            addCriterion("COLM_CODE is null");
            return (Criteria) this;
        }

        public Criteria andColmCodeIsNotNull() {
            addCriterion("COLM_CODE is not null");
            return (Criteria) this;
        }

        public Criteria andColmCodeEqualTo(String value) {
            addCriterion("COLM_CODE =", value, "colmCode");
            return (Criteria) this;
        }

        public Criteria andColmCodeNotEqualTo(String value) {
            addCriterion("COLM_CODE <>", value, "colmCode");
            return (Criteria) this;
        }

        public Criteria andColmCodeGreaterThan(String value) {
            addCriterion("COLM_CODE >", value, "colmCode");
            return (Criteria) this;
        }

        public Criteria andColmCodeGreaterThanOrEqualTo(String value) {
            addCriterion("COLM_CODE >=", value, "colmCode");
            return (Criteria) this;
        }

        public Criteria andColmCodeLessThan(String value) {
            addCriterion("COLM_CODE <", value, "colmCode");
            return (Criteria) this;
        }

        public Criteria andColmCodeLessThanOrEqualTo(String value) {
            addCriterion("COLM_CODE <=", value, "colmCode");
            return (Criteria) this;
        }

        public Criteria andColmCodeLike(String value) {
            addCriterion("COLM_CODE like", value, "colmCode");
            return (Criteria) this;
        }

        public Criteria andColmCodeNotLike(String value) {
            addCriterion("COLM_CODE not like", value, "colmCode");
            return (Criteria) this;
        }

        public Criteria andColmCodeIn(List<String> values) {
            addCriterion("COLM_CODE in", values, "colmCode");
            return (Criteria) this;
        }

        public Criteria andColmCodeNotIn(List<String> values) {
            addCriterion("COLM_CODE not in", values, "colmCode");
            return (Criteria) this;
        }

        public Criteria andColmCodeBetween(String value1, String value2) {
            addCriterion("COLM_CODE between", value1, value2, "colmCode");
            return (Criteria) this;
        }

        public Criteria andColmCodeNotBetween(String value1, String value2) {
            addCriterion("COLM_CODE not between", value1, value2, "colmCode");
            return (Criteria) this;
        }

        public Criteria andTsvldRegexpIsNull() {
            addCriterion("TSVLD_REGEXP is null");
            return (Criteria) this;
        }

        public Criteria andTsvldRegexpIsNotNull() {
            addCriterion("TSVLD_REGEXP is not null");
            return (Criteria) this;
        }

        public Criteria andTsvldRegexpEqualTo(String value) {
            addCriterion("TSVLD_REGEXP =", value, "tsvldRegexp");
            return (Criteria) this;
        }

        public Criteria andTsvldRegexpNotEqualTo(String value) {
            addCriterion("TSVLD_REGEXP <>", value, "tsvldRegexp");
            return (Criteria) this;
        }

        public Criteria andTsvldRegexpGreaterThan(String value) {
            addCriterion("TSVLD_REGEXP >", value, "tsvldRegexp");
            return (Criteria) this;
        }

        public Criteria andTsvldRegexpGreaterThanOrEqualTo(String value) {
            addCriterion("TSVLD_REGEXP >=", value, "tsvldRegexp");
            return (Criteria) this;
        }

        public Criteria andTsvldRegexpLessThan(String value) {
            addCriterion("TSVLD_REGEXP <", value, "tsvldRegexp");
            return (Criteria) this;
        }

        public Criteria andTsvldRegexpLessThanOrEqualTo(String value) {
            addCriterion("TSVLD_REGEXP <=", value, "tsvldRegexp");
            return (Criteria) this;
        }

        public Criteria andTsvldRegexpLike(String value) {
            addCriterion("TSVLD_REGEXP like", value, "tsvldRegexp");
            return (Criteria) this;
        }

        public Criteria andTsvldRegexpNotLike(String value) {
            addCriterion("TSVLD_REGEXP not like", value, "tsvldRegexp");
            return (Criteria) this;
        }

        public Criteria andTsvldRegexpIn(List<String> values) {
            addCriterion("TSVLD_REGEXP in", values, "tsvldRegexp");
            return (Criteria) this;
        }

        public Criteria andTsvldRegexpNotIn(List<String> values) {
            addCriterion("TSVLD_REGEXP not in", values, "tsvldRegexp");
            return (Criteria) this;
        }

        public Criteria andTsvldRegexpBetween(String value1, String value2) {
            addCriterion("TSVLD_REGEXP between", value1, value2, "tsvldRegexp");
            return (Criteria) this;
        }

        public Criteria andTsvldRegexpNotBetween(String value1, String value2) {
            addCriterion("TSVLD_REGEXP not between", value1, value2, "tsvldRegexp");
            return (Criteria) this;
        }

        public Criteria andHintCnttIsNull() {
            addCriterion("HINT_CNTT is null");
            return (Criteria) this;
        }

        public Criteria andHintCnttIsNotNull() {
            addCriterion("HINT_CNTT is not null");
            return (Criteria) this;
        }

        public Criteria andHintCnttEqualTo(String value) {
            addCriterion("HINT_CNTT =", value, "hintCntt");
            return (Criteria) this;
        }

        public Criteria andHintCnttNotEqualTo(String value) {
            addCriterion("HINT_CNTT <>", value, "hintCntt");
            return (Criteria) this;
        }

        public Criteria andHintCnttGreaterThan(String value) {
            addCriterion("HINT_CNTT >", value, "hintCntt");
            return (Criteria) this;
        }

        public Criteria andHintCnttGreaterThanOrEqualTo(String value) {
            addCriterion("HINT_CNTT >=", value, "hintCntt");
            return (Criteria) this;
        }

        public Criteria andHintCnttLessThan(String value) {
            addCriterion("HINT_CNTT <", value, "hintCntt");
            return (Criteria) this;
        }

        public Criteria andHintCnttLessThanOrEqualTo(String value) {
            addCriterion("HINT_CNTT <=", value, "hintCntt");
            return (Criteria) this;
        }

        public Criteria andHintCnttLike(String value) {
            addCriterion("HINT_CNTT like", value, "hintCntt");
            return (Criteria) this;
        }

        public Criteria andHintCnttNotLike(String value) {
            addCriterion("HINT_CNTT not like", value, "hintCntt");
            return (Criteria) this;
        }

        public Criteria andHintCnttIn(List<String> values) {
            addCriterion("HINT_CNTT in", values, "hintCntt");
            return (Criteria) this;
        }

        public Criteria andHintCnttNotIn(List<String> values) {
            addCriterion("HINT_CNTT not in", values, "hintCntt");
            return (Criteria) this;
        }

        public Criteria andHintCnttBetween(String value1, String value2) {
            addCriterion("HINT_CNTT between", value1, value2, "hintCntt");
            return (Criteria) this;
        }

        public Criteria andHintCnttNotBetween(String value1, String value2) {
            addCriterion("HINT_CNTT not between", value1, value2, "hintCntt");
            return (Criteria) this;
        }

        public Criteria andRequiredFlagIsNull() {
            addCriterion("REQUIRED_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andRequiredFlagIsNotNull() {
            addCriterion("REQUIRED_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andRequiredFlagEqualTo(Byte value) {
            addCriterion("REQUIRED_FLAG =", value, "requiredFlag");
            return (Criteria) this;
        }

        public Criteria andRequiredFlagNotEqualTo(Byte value) {
            addCriterion("REQUIRED_FLAG <>", value, "requiredFlag");
            return (Criteria) this;
        }

        public Criteria andRequiredFlagGreaterThan(Byte value) {
            addCriterion("REQUIRED_FLAG >", value, "requiredFlag");
            return (Criteria) this;
        }

        public Criteria andRequiredFlagGreaterThanOrEqualTo(Byte value) {
            addCriterion("REQUIRED_FLAG >=", value, "requiredFlag");
            return (Criteria) this;
        }

        public Criteria andRequiredFlagLessThan(Byte value) {
            addCriterion("REQUIRED_FLAG <", value, "requiredFlag");
            return (Criteria) this;
        }

        public Criteria andRequiredFlagLessThanOrEqualTo(Byte value) {
            addCriterion("REQUIRED_FLAG <=", value, "requiredFlag");
            return (Criteria) this;
        }

        public Criteria andRequiredFlagIn(List<Byte> values) {
            addCriterion("REQUIRED_FLAG in", values, "requiredFlag");
            return (Criteria) this;
        }

        public Criteria andRequiredFlagNotIn(List<Byte> values) {
            addCriterion("REQUIRED_FLAG not in", values, "requiredFlag");
            return (Criteria) this;
        }

        public Criteria andRequiredFlagBetween(Byte value1, Byte value2) {
            addCriterion("REQUIRED_FLAG between", value1, value2, "requiredFlag");
            return (Criteria) this;
        }

        public Criteria andRequiredFlagNotBetween(Byte value1, Byte value2) {
            addCriterion("REQUIRED_FLAG not between", value1, value2, "requiredFlag");
            return (Criteria) this;
        }

        public Criteria andFltrCondFlagIsNull() {
            addCriterion("FLTR_COND_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andFltrCondFlagIsNotNull() {
            addCriterion("FLTR_COND_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andFltrCondFlagEqualTo(Byte value) {
            addCriterion("FLTR_COND_FLAG =", value, "fltrCondFlag");
            return (Criteria) this;
        }

        public Criteria andFltrCondFlagNotEqualTo(Byte value) {
            addCriterion("FLTR_COND_FLAG <>", value, "fltrCondFlag");
            return (Criteria) this;
        }

        public Criteria andFltrCondFlagGreaterThan(Byte value) {
            addCriterion("FLTR_COND_FLAG >", value, "fltrCondFlag");
            return (Criteria) this;
        }

        public Criteria andFltrCondFlagGreaterThanOrEqualTo(Byte value) {
            addCriterion("FLTR_COND_FLAG >=", value, "fltrCondFlag");
            return (Criteria) this;
        }

        public Criteria andFltrCondFlagLessThan(Byte value) {
            addCriterion("FLTR_COND_FLAG <", value, "fltrCondFlag");
            return (Criteria) this;
        }

        public Criteria andFltrCondFlagLessThanOrEqualTo(Byte value) {
            addCriterion("FLTR_COND_FLAG <=", value, "fltrCondFlag");
            return (Criteria) this;
        }

        public Criteria andFltrCondFlagIn(List<Byte> values) {
            addCriterion("FLTR_COND_FLAG in", values, "fltrCondFlag");
            return (Criteria) this;
        }

        public Criteria andFltrCondFlagNotIn(List<Byte> values) {
            addCriterion("FLTR_COND_FLAG not in", values, "fltrCondFlag");
            return (Criteria) this;
        }

        public Criteria andFltrCondFlagBetween(Byte value1, Byte value2) {
            addCriterion("FLTR_COND_FLAG between", value1, value2, "fltrCondFlag");
            return (Criteria) this;
        }

        public Criteria andFltrCondFlagNotBetween(Byte value1, Byte value2) {
            addCriterion("FLTR_COND_FLAG not between", value1, value2, "fltrCondFlag");
            return (Criteria) this;
        }

        public Criteria andArgeSeqnoIsNull() {
            addCriterion("ARGE_SEQNO is null");
            return (Criteria) this;
        }

        public Criteria andArgeSeqnoIsNotNull() {
            addCriterion("ARGE_SEQNO is not null");
            return (Criteria) this;
        }

        public Criteria andArgeSeqnoEqualTo(Short value) {
            addCriterion("ARGE_SEQNO =", value, "argeSeqno");
            return (Criteria) this;
        }

        public Criteria andArgeSeqnoNotEqualTo(Short value) {
            addCriterion("ARGE_SEQNO <>", value, "argeSeqno");
            return (Criteria) this;
        }

        public Criteria andArgeSeqnoGreaterThan(Short value) {
            addCriterion("ARGE_SEQNO >", value, "argeSeqno");
            return (Criteria) this;
        }

        public Criteria andArgeSeqnoGreaterThanOrEqualTo(Short value) {
            addCriterion("ARGE_SEQNO >=", value, "argeSeqno");
            return (Criteria) this;
        }

        public Criteria andArgeSeqnoLessThan(Short value) {
            addCriterion("ARGE_SEQNO <", value, "argeSeqno");
            return (Criteria) this;
        }

        public Criteria andArgeSeqnoLessThanOrEqualTo(Short value) {
            addCriterion("ARGE_SEQNO <=", value, "argeSeqno");
            return (Criteria) this;
        }

        public Criteria andArgeSeqnoIn(List<Short> values) {
            addCriterion("ARGE_SEQNO in", values, "argeSeqno");
            return (Criteria) this;
        }

        public Criteria andArgeSeqnoNotIn(List<Short> values) {
            addCriterion("ARGE_SEQNO not in", values, "argeSeqno");
            return (Criteria) this;
        }

        public Criteria andArgeSeqnoBetween(Short value1, Short value2) {
            addCriterion("ARGE_SEQNO between", value1, value2, "argeSeqno");
            return (Criteria) this;
        }

        public Criteria andArgeSeqnoNotBetween(Short value1, Short value2) {
            addCriterion("ARGE_SEQNO not between", value1, value2, "argeSeqno");
            return (Criteria) this;
        }

        public Criteria andColmDescIsNull() {
            addCriterion("COLM_DESC is null");
            return (Criteria) this;
        }

        public Criteria andColmDescIsNotNull() {
            addCriterion("COLM_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andColmDescEqualTo(String value) {
            addCriterion("COLM_DESC =", value, "colmDesc");
            return (Criteria) this;
        }

        public Criteria andColmDescNotEqualTo(String value) {
            addCriterion("COLM_DESC <>", value, "colmDesc");
            return (Criteria) this;
        }

        public Criteria andColmDescGreaterThan(String value) {
            addCriterion("COLM_DESC >", value, "colmDesc");
            return (Criteria) this;
        }

        public Criteria andColmDescGreaterThanOrEqualTo(String value) {
            addCriterion("COLM_DESC >=", value, "colmDesc");
            return (Criteria) this;
        }

        public Criteria andColmDescLessThan(String value) {
            addCriterion("COLM_DESC <", value, "colmDesc");
            return (Criteria) this;
        }

        public Criteria andColmDescLessThanOrEqualTo(String value) {
            addCriterion("COLM_DESC <=", value, "colmDesc");
            return (Criteria) this;
        }

        public Criteria andColmDescLike(String value) {
            addCriterion("COLM_DESC like", value, "colmDesc");
            return (Criteria) this;
        }

        public Criteria andColmDescNotLike(String value) {
            addCriterion("COLM_DESC not like", value, "colmDesc");
            return (Criteria) this;
        }

        public Criteria andColmDescIn(List<String> values) {
            addCriterion("COLM_DESC in", values, "colmDesc");
            return (Criteria) this;
        }

        public Criteria andColmDescNotIn(List<String> values) {
            addCriterion("COLM_DESC not in", values, "colmDesc");
            return (Criteria) this;
        }

        public Criteria andColmDescBetween(String value1, String value2) {
            addCriterion("COLM_DESC between", value1, value2, "colmDesc");
            return (Criteria) this;
        }

        public Criteria andColmDescNotBetween(String value1, String value2) {
            addCriterion("COLM_DESC not between", value1, value2, "colmDesc");
            return (Criteria) this;
        }

        public Criteria andOpPrsnIdIsNull() {
            addCriterion("OP_PRSN_ID is null");
            return (Criteria) this;
        }

        public Criteria andOpPrsnIdIsNotNull() {
            addCriterion("OP_PRSN_ID is not null");
            return (Criteria) this;
        }

        public Criteria andOpPrsnIdEqualTo(String value) {
            addCriterion("OP_PRSN_ID =", value, "opPrsnId");
            return (Criteria) this;
        }

        public Criteria andOpPrsnIdNotEqualTo(String value) {
            addCriterion("OP_PRSN_ID <>", value, "opPrsnId");
            return (Criteria) this;
        }

        public Criteria andOpPrsnIdGreaterThan(String value) {
            addCriterion("OP_PRSN_ID >", value, "opPrsnId");
            return (Criteria) this;
        }

        public Criteria andOpPrsnIdGreaterThanOrEqualTo(String value) {
            addCriterion("OP_PRSN_ID >=", value, "opPrsnId");
            return (Criteria) this;
        }

        public Criteria andOpPrsnIdLessThan(String value) {
            addCriterion("OP_PRSN_ID <", value, "opPrsnId");
            return (Criteria) this;
        }

        public Criteria andOpPrsnIdLessThanOrEqualTo(String value) {
            addCriterion("OP_PRSN_ID <=", value, "opPrsnId");
            return (Criteria) this;
        }

        public Criteria andOpPrsnIdLike(String value) {
            addCriterion("OP_PRSN_ID like", value, "opPrsnId");
            return (Criteria) this;
        }

        public Criteria andOpPrsnIdNotLike(String value) {
            addCriterion("OP_PRSN_ID not like", value, "opPrsnId");
            return (Criteria) this;
        }

        public Criteria andOpPrsnIdIn(List<String> values) {
            addCriterion("OP_PRSN_ID in", values, "opPrsnId");
            return (Criteria) this;
        }

        public Criteria andOpPrsnIdNotIn(List<String> values) {
            addCriterion("OP_PRSN_ID not in", values, "opPrsnId");
            return (Criteria) this;
        }

        public Criteria andOpPrsnIdBetween(String value1, String value2) {
            addCriterion("OP_PRSN_ID between", value1, value2, "opPrsnId");
            return (Criteria) this;
        }

        public Criteria andOpPrsnIdNotBetween(String value1, String value2) {
            addCriterion("OP_PRSN_ID not between", value1, value2, "opPrsnId");
            return (Criteria) this;
        }

        public Criteria andCrtTimeIsNull() {
            addCriterion("CRT_TIME is null");
            return (Criteria) this;
        }

        public Criteria andCrtTimeIsNotNull() {
            addCriterion("CRT_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andCrtTimeEqualTo(Timestamp value) {
            addCriterion("CRT_TIME =", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotEqualTo(Timestamp value) {
            addCriterion("CRT_TIME <>", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeGreaterThan(Timestamp value) {
            addCriterion("CRT_TIME >", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("CRT_TIME >=", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeLessThan(Timestamp value) {
            addCriterion("CRT_TIME <", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("CRT_TIME <=", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeIn(List<Timestamp> values) {
            addCriterion("CRT_TIME in", values, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotIn(List<Timestamp> values) {
            addCriterion("CRT_TIME not in", values, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("CRT_TIME between", value1, value2, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("CRT_TIME not between", value1, value2, "crtTime");
            return (Criteria) this;
        }

        public Criteria andModfTimeIsNull() {
            addCriterion("MODF_TIME is null");
            return (Criteria) this;
        }

        public Criteria andModfTimeIsNotNull() {
            addCriterion("MODF_TIME is not null");
            return (Criteria) this;
        }

        public Criteria andModfTimeEqualTo(Timestamp value) {
            addCriterion("MODF_TIME =", value, "modfTime");
            return (Criteria) this;
        }

        public Criteria andModfTimeNotEqualTo(Timestamp value) {
            addCriterion("MODF_TIME <>", value, "modfTime");
            return (Criteria) this;
        }

        public Criteria andModfTimeGreaterThan(Timestamp value) {
            addCriterion("MODF_TIME >", value, "modfTime");
            return (Criteria) this;
        }

        public Criteria andModfTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("MODF_TIME >=", value, "modfTime");
            return (Criteria) this;
        }

        public Criteria andModfTimeLessThan(Timestamp value) {
            addCriterion("MODF_TIME <", value, "modfTime");
            return (Criteria) this;
        }

        public Criteria andModfTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("MODF_TIME <=", value, "modfTime");
            return (Criteria) this;
        }

        public Criteria andModfTimeIn(List<Timestamp> values) {
            addCriterion("MODF_TIME in", values, "modfTime");
            return (Criteria) this;
        }

        public Criteria andModfTimeNotIn(List<Timestamp> values) {
            addCriterion("MODF_TIME not in", values, "modfTime");
            return (Criteria) this;
        }

        public Criteria andModfTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("MODF_TIME between", value1, value2, "modfTime");
            return (Criteria) this;
        }

        public Criteria andModfTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("MODF_TIME not between", value1, value2, "modfTime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_km_consult_keys
     *
     * @mbggenerated do_not_delete_during_merge Tue Feb 27 15:43:36 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_km_consult_keys
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}