package com.jw.consult.dao;

import com.jw.consult.bean.TKmConsultApply;
import com.jw.consult.bean.TKmConsultApplyExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface TKmConsultApplyDAO {

    Integer countListConsultApply(Map<String,Object> condition);
    List<TKmConsultApply> listConsultApply(Map<String,Object> condition);
    /**
     * 查询咨询表应用的id的集合
     *
     * @param condition
     * @return
     */
    List<Long> getConsultIds(Map<String, Object> condition);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_apply
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int countByExample(TKmConsultApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_apply
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int deleteByExample(TKmConsultApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_apply
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int deleteByPrimaryKey(Long cnslId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_apply
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int save(TKmConsultApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_apply
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int saveSelective(TKmConsultApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_apply
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    List<TKmConsultApply> selectByExample(TKmConsultApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_apply
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    TKmConsultApply selectByPrimaryKey(Long cnslId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_apply
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") TKmConsultApply record, @Param("example") TKmConsultApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_apply
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int updateByExample(@Param("record") TKmConsultApply record, @Param("example") TKmConsultApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_apply
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int updateByPrimaryKeySelective(TKmConsultApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_apply
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int updateByPrimaryKey(TKmConsultApply record);
}