package com.jw.consult.dao;

import com.jw.consult.bean.TKmConsultCatl;
import com.jw.consult.bean.TKmConsultCatlExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface TKmConsultCatlDAO {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_catl
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int countByExample(TKmConsultCatlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_catl
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int deleteByExample(TKmConsultCatlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_catl
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int deleteByPrimaryKey(Long catlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_catl
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int save(TKmConsultCatl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_catl
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int saveSelective(TKmConsultCatl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_catl
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    List<TKmConsultCatl> selectByExample(TKmConsultCatlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_catl
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    TKmConsultCatl selectByPrimaryKey(Long catlId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_catl
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") TKmConsultCatl record, @Param("example") TKmConsultCatlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_catl
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int updateByExample(@Param("record") TKmConsultCatl record, @Param("example") TKmConsultCatlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_catl
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int updateByPrimaryKeySelective(TKmConsultCatl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_catl
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int updateByPrimaryKey(TKmConsultCatl record);

    List getConsultCatl(TKmConsultCatl tKmConsultCatl);

    String getConsultCatlMaxSeqno(TKmConsultCatl tKmConsultCatl);

}