package com.jw.consult.dao;

import com.jw.consult.bean.TKmConsultTmplt;
import com.jw.consult.bean.TKmConsultTmpltExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface TKmConsultTmpltDAO {

    /**
     * 不带分页条件查询模板列表
     *
     * @param tKmConsultTmplt
     * @return
     */
    List<TKmConsultTmplt> getTmpltListNoPage(TKmConsultTmplt tKmConsultTmplt);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_tmplt
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int countByExample(TKmConsultTmpltExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_tmplt
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int deleteByExample(TKmConsultTmpltExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_tmplt
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int deleteByPrimaryKey(Long tmpltId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_tmplt
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int save(TKmConsultTmplt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_tmplt
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int saveSelective(TKmConsultTmplt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_tmplt
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    List<TKmConsultTmplt> selectByExample(TKmConsultTmpltExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_tmplt
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    TKmConsultTmplt selectByPrimaryKey(Long tmpltId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_tmplt
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") TKmConsultTmplt record, @Param("example") TKmConsultTmpltExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_tmplt
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int updateByExample(@Param("record") TKmConsultTmplt record, @Param("example") TKmConsultTmpltExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_tmplt
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int updateByPrimaryKeySelective(TKmConsultTmplt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_tmplt
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int updateByPrimaryKey(TKmConsultTmplt record);

    /**
     * 查询模板列表
     * @param paramMap
     * @return
     */
    List<TKmConsultTmplt> getConsultTmpltList(Map paramMap);

    /**
     * 查询模板列表总数
     * @param paramMap
     * @return
     */
    int getConsultTmpltListCount(Map paramMap);

    /**
     * 查询目录下最大的排列序号
     * @param catlId
     * @return argeSeqno
     */
    Short getMaxArgeSeqnoByCaltId(Long catlId);
}