package com.jw.consult.dao;

import com.jw.consult.bean.TKmConsultData;
import com.jw.consult.bean.TKmConsultDataExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface TKmConsultDataDAO {

    /**
     * 查询某一咨询表记录详细信息
     *
     * @param condition
     * @return
     */
    List<TKmConsultData> getConsultData(Map<String, Object> condition);

    /**
     * 批量保存记录
     *
     * @param condition
     */
    void saveDataMult(Map<String, Object> condition);
    /**
     * 查询记录id
     *
     * @param condition
     * @return
     */
    List<Long> getCnttIds(Map<String, Object> condition);

    /**
     * 批量删除
     *
     * @param condition
     */
    void deleteMult(Map<String, Object> condition);

    /**
     * 保存记录数据
     *
     * @param kmConsultData
     */
    void saveConsultData(TKmConsultData kmConsultData);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_data
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int countByExample(TKmConsultDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_data
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int deleteByExample(TKmConsultDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_data
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int deleteByPrimaryKey(Long cnttId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_data
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int save(TKmConsultData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_data
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int saveSelective(TKmConsultData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_data
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    List<TKmConsultData> selectByExample(TKmConsultDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_data
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    TKmConsultData selectByPrimaryKey(Long cnttId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_data
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") TKmConsultData record, @Param("example") TKmConsultDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_data
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int updateByExample(@Param("record") TKmConsultData record, @Param("example") TKmConsultDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_data
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int updateByPrimaryKeySelective(TKmConsultData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_data
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int updateByPrimaryKey(TKmConsultData record);
}