package com.jw.consult.dao;

import com.jw.consult.bean.TKmConsultRowsXxx;
import com.jw.consult.bean.TKmConsultRowsXxxExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;
import java.util.Map;

public interface TKmConsultRowsXxxDAO {

    /**
     * 查询某一记录详细信息
     *
     * @param condition
     * @return
     */
    TKmConsultRowsXxx getRecMessage(Map<String, Object> condition);

    /**
     * 查询咨询表记录id
     *
     * @param condition
     * @return
     */
    List<Long> getRecIds(Map<String, Object> condition);

    /**
     * 查询某一咨询表下的记录总数
     *
     * @param condition
     * @return
     */
    int getConsultCount(Map<String, Object> condition);

    /**
     * 更新行记录
     *
     * @param condition
     */
    void updateConsultRows(Map<String, Object> condition);

    /**
     * 删除咨询表行记录
     *
     * @param condition
     */
    void deleteConsultRows(Map<String, Object> condition);

    /**
     * 新增记录
     *
     * @param consultRowsXxx
     */
    void saveConsultRows(TKmConsultRowsXxx consultRowsXxx);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_rows_xxx
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int countByExample(TKmConsultRowsXxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_rows_xxx
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int deleteByExample(TKmConsultRowsXxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_rows_xxx
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int deleteByPrimaryKey(Long recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_rows_xxx
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int save(TKmConsultRowsXxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_rows_xxx
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int saveSelective(TKmConsultRowsXxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_rows_xxx
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    List<TKmConsultRowsXxx> selectByExample(TKmConsultRowsXxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_rows_xxx
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    TKmConsultRowsXxx selectByPrimaryKey(Long recId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_rows_xxx
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int updateByExampleSelective(@Param("record") TKmConsultRowsXxx record, @Param("example") TKmConsultRowsXxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_rows_xxx
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int updateByExample(@Param("record") TKmConsultRowsXxx record, @Param("example") TKmConsultRowsXxxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_rows_xxx
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int updateByPrimaryKeySelective(TKmConsultRowsXxx record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_km_consult_rows_xxx
     *
     * @mbggenerated Tue Feb 27 15:43:36 CST 2018
     */
    int updateByPrimaryKey(TKmConsultRowsXxx record);
}