package com.jw.shiro.bean;

import java.sql.Timestamp;

public class TSysUserRole {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user_role.rl_id
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    private Long rlId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user_role.u_id
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    private Long uId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user_role.role_id
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    private Long roleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user_role.crt_time
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    private Timestamp crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user_role.modf_time
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    private Timestamp modfTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user_role.operator
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    private Long operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_sys_user_role.rmk
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    private String rmk;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user_role
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    public TSysUserRole(Long rlId, Long uId, Long roleId, Timestamp crtTime, Timestamp modfTime, Long operator, String rmk) {
        this.rlId = rlId;
        this.uId = uId;
        this.roleId = roleId;
        this.crtTime = crtTime;
        this.modfTime = modfTime;
        this.operator = operator;
        this.rmk = rmk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_sys_user_role
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    public TSysUserRole() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user_role.rl_id
     *
     * @return the value of t_sys_user_role.rl_id
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    public Long getRlId() {
        return rlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user_role.rl_id
     *
     * @param rlId the value for t_sys_user_role.rl_id
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    public void setRlId(Long rlId) {
        this.rlId = rlId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user_role.u_id
     *
     * @return the value of t_sys_user_role.u_id
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    public Long getuId() {
        return uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user_role.u_id
     *
     * @param uId the value for t_sys_user_role.u_id
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    public void setuId(Long uId) {
        this.uId = uId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user_role.role_id
     *
     * @return the value of t_sys_user_role.role_id
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    public Long getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user_role.role_id
     *
     * @param roleId the value for t_sys_user_role.role_id
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user_role.crt_time
     *
     * @return the value of t_sys_user_role.crt_time
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    public Timestamp getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user_role.crt_time
     *
     * @param crtTime the value for t_sys_user_role.crt_time
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    public void setCrtTime(Timestamp crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user_role.modf_time
     *
     * @return the value of t_sys_user_role.modf_time
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    public Timestamp getModfTime() {
        return modfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user_role.modf_time
     *
     * @param modfTime the value for t_sys_user_role.modf_time
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    public void setModfTime(Timestamp modfTime) {
        this.modfTime = modfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user_role.operator
     *
     * @return the value of t_sys_user_role.operator
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    public Long getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user_role.operator
     *
     * @param operator the value for t_sys_user_role.operator
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    public void setOperator(Long operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_sys_user_role.rmk
     *
     * @return the value of t_sys_user_role.rmk
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    public String getRmk() {
        return rmk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_sys_user_role.rmk
     *
     * @param rmk the value for t_sys_user_role.rmk
     *
     * @mbggenerated Sun Aug 19 14:01:10 CST 2018
     */
    public void setRmk(String rmk) {
        this.rmk = rmk == null ? null : rmk.trim();
    }
}