package com.jw.kids.bean;

import java.sql.Timestamp;

public class TClassLogDetail {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_log_detail.detail_log_id
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    private Long detailLogId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_log_detail.log_id
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    private Long logId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_log_detail.log_type
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    private Byte logType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_log_detail.log_obj_id
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    private Long logObjId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_log_detail.unit
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    private Short unit;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_log_detail.crt_time
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    private Timestamp crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_log_detail.class_time
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    private Timestamp classTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_log_detail.operator
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    private Long operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_class_log_detail.rmk
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    private String rmk;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_log_detail
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    public TClassLogDetail(Long detailLogId, Long logId, Byte logType, Long logObjId, Short unit, Timestamp crtTime, Timestamp classTime, Long operator, String rmk) {
        this.detailLogId = detailLogId;
        this.logId = logId;
        this.logType = logType;
        this.logObjId = logObjId;
        this.unit = unit;
        this.crtTime = crtTime;
        this.classTime = classTime;
        this.operator = operator;
        this.rmk = rmk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_class_log_detail
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    public TClassLogDetail() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_log_detail.detail_log_id
     *
     * @return the value of t_class_log_detail.detail_log_id
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    public Long getDetailLogId() {
        return detailLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_log_detail.detail_log_id
     *
     * @param detailLogId the value for t_class_log_detail.detail_log_id
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    public void setDetailLogId(Long detailLogId) {
        this.detailLogId = detailLogId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_log_detail.log_id
     *
     * @return the value of t_class_log_detail.log_id
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    public Long getLogId() {
        return logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_log_detail.log_id
     *
     * @param logId the value for t_class_log_detail.log_id
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    public void setLogId(Long logId) {
        this.logId = logId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_log_detail.log_type
     *
     * @return the value of t_class_log_detail.log_type
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    public Byte getLogType() {
        return logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_log_detail.log_type
     *
     * @param logType the value for t_class_log_detail.log_type
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    public void setLogType(Byte logType) {
        this.logType = logType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_log_detail.log_obj_id
     *
     * @return the value of t_class_log_detail.log_obj_id
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    public Long getLogObjId() {
        return logObjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_log_detail.log_obj_id
     *
     * @param logObjId the value for t_class_log_detail.log_obj_id
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    public void setLogObjId(Long logObjId) {
        this.logObjId = logObjId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_log_detail.unit
     *
     * @return the value of t_class_log_detail.unit
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    public Short getUnit() {
        return unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_log_detail.unit
     *
     * @param unit the value for t_class_log_detail.unit
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    public void setUnit(Short unit) {
        this.unit = unit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_log_detail.crt_time
     *
     * @return the value of t_class_log_detail.crt_time
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    public Timestamp getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_log_detail.crt_time
     *
     * @param crtTime the value for t_class_log_detail.crt_time
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    public void setCrtTime(Timestamp crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_log_detail.class_time
     *
     * @return the value of t_class_log_detail.class_time
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    public Timestamp getClassTime() {
        return classTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_log_detail.class_time
     *
     * @param classTime the value for t_class_log_detail.class_time
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    public void setClassTime(Timestamp classTime) {
        this.classTime = classTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_log_detail.operator
     *
     * @return the value of t_class_log_detail.operator
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    public Long getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_log_detail.operator
     *
     * @param operator the value for t_class_log_detail.operator
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    public void setOperator(Long operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_class_log_detail.rmk
     *
     * @return the value of t_class_log_detail.rmk
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    public String getRmk() {
        return rmk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_class_log_detail.rmk
     *
     * @param rmk the value for t_class_log_detail.rmk
     *
     * @mbggenerated Wed Aug 08 23:12:38 CST 2018
     */
    public void setRmk(String rmk) {
        this.rmk = rmk == null ? null : rmk.trim();
    }
}