package com.jw.kids.bean;

import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;

public class TTeacherExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_teacher
     *
     * @mbggenerated Sun Aug 05 22:05:07 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_teacher
     *
     * @mbggenerated Sun Aug 05 22:05:07 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_teacher
     *
     * @mbggenerated Sun Aug 05 22:05:07 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher
     *
     * @mbggenerated Sun Aug 05 22:05:07 CST 2018
     */
    public TTeacherExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher
     *
     * @mbggenerated Sun Aug 05 22:05:07 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher
     *
     * @mbggenerated Sun Aug 05 22:05:07 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher
     *
     * @mbggenerated Sun Aug 05 22:05:07 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher
     *
     * @mbggenerated Sun Aug 05 22:05:07 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher
     *
     * @mbggenerated Sun Aug 05 22:05:07 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher
     *
     * @mbggenerated Sun Aug 05 22:05:07 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher
     *
     * @mbggenerated Sun Aug 05 22:05:07 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher
     *
     * @mbggenerated Sun Aug 05 22:05:07 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher
     *
     * @mbggenerated Sun Aug 05 22:05:07 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher
     *
     * @mbggenerated Sun Aug 05 22:05:07 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_teacher
     *
     * @mbggenerated Sun Aug 05 22:05:07 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTeacherIdIsNull() {
            addCriterion("teacher_id is null");
            return (Criteria) this;
        }

        public Criteria andTeacherIdIsNotNull() {
            addCriterion("teacher_id is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherIdEqualTo(Long value) {
            addCriterion("teacher_id =", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdNotEqualTo(Long value) {
            addCriterion("teacher_id <>", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdGreaterThan(Long value) {
            addCriterion("teacher_id >", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdGreaterThanOrEqualTo(Long value) {
            addCriterion("teacher_id >=", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdLessThan(Long value) {
            addCriterion("teacher_id <", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdLessThanOrEqualTo(Long value) {
            addCriterion("teacher_id <=", value, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdIn(List<Long> values) {
            addCriterion("teacher_id in", values, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdNotIn(List<Long> values) {
            addCriterion("teacher_id not in", values, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdBetween(Long value1, Long value2) {
            addCriterion("teacher_id between", value1, value2, "teacherId");
            return (Criteria) this;
        }

        public Criteria andTeacherIdNotBetween(Long value1, Long value2) {
            addCriterion("teacher_id not between", value1, value2, "teacherId");
            return (Criteria) this;
        }

        public Criteria andDutyIsNull() {
            addCriterion("duty is null");
            return (Criteria) this;
        }

        public Criteria andDutyIsNotNull() {
            addCriterion("duty is not null");
            return (Criteria) this;
        }

        public Criteria andDutyEqualTo(Integer value) {
            addCriterion("duty =", value, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyNotEqualTo(Integer value) {
            addCriterion("duty <>", value, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyGreaterThan(Integer value) {
            addCriterion("duty >", value, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyGreaterThanOrEqualTo(Integer value) {
            addCriterion("duty >=", value, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyLessThan(Integer value) {
            addCriterion("duty <", value, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyLessThanOrEqualTo(Integer value) {
            addCriterion("duty <=", value, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyIn(List<Integer> values) {
            addCriterion("duty in", values, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyNotIn(List<Integer> values) {
            addCriterion("duty not in", values, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyBetween(Integer value1, Integer value2) {
            addCriterion("duty between", value1, value2, "duty");
            return (Criteria) this;
        }

        public Criteria andDutyNotBetween(Integer value1, Integer value2) {
            addCriterion("duty not between", value1, value2, "duty");
            return (Criteria) this;
        }

        public Criteria andTeacherNmIsNull() {
            addCriterion("teacher_nm is null");
            return (Criteria) this;
        }

        public Criteria andTeacherNmIsNotNull() {
            addCriterion("teacher_nm is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherNmEqualTo(String value) {
            addCriterion("teacher_nm =", value, "teacherNm");
            return (Criteria) this;
        }

        public Criteria andTeacherNmNotEqualTo(String value) {
            addCriterion("teacher_nm <>", value, "teacherNm");
            return (Criteria) this;
        }

        public Criteria andTeacherNmGreaterThan(String value) {
            addCriterion("teacher_nm >", value, "teacherNm");
            return (Criteria) this;
        }

        public Criteria andTeacherNmGreaterThanOrEqualTo(String value) {
            addCriterion("teacher_nm >=", value, "teacherNm");
            return (Criteria) this;
        }

        public Criteria andTeacherNmLessThan(String value) {
            addCriterion("teacher_nm <", value, "teacherNm");
            return (Criteria) this;
        }

        public Criteria andTeacherNmLessThanOrEqualTo(String value) {
            addCriterion("teacher_nm <=", value, "teacherNm");
            return (Criteria) this;
        }

        public Criteria andTeacherNmLike(String value) {
            addCriterion("teacher_nm like", value, "teacherNm");
            return (Criteria) this;
        }

        public Criteria andTeacherNmNotLike(String value) {
            addCriterion("teacher_nm not like", value, "teacherNm");
            return (Criteria) this;
        }

        public Criteria andTeacherNmIn(List<String> values) {
            addCriterion("teacher_nm in", values, "teacherNm");
            return (Criteria) this;
        }

        public Criteria andTeacherNmNotIn(List<String> values) {
            addCriterion("teacher_nm not in", values, "teacherNm");
            return (Criteria) this;
        }

        public Criteria andTeacherNmBetween(String value1, String value2) {
            addCriterion("teacher_nm between", value1, value2, "teacherNm");
            return (Criteria) this;
        }

        public Criteria andTeacherNmNotBetween(String value1, String value2) {
            addCriterion("teacher_nm not between", value1, value2, "teacherNm");
            return (Criteria) this;
        }

        public Criteria andTeacherEnNmIsNull() {
            addCriterion("teacher_en_nm is null");
            return (Criteria) this;
        }

        public Criteria andTeacherEnNmIsNotNull() {
            addCriterion("teacher_en_nm is not null");
            return (Criteria) this;
        }

        public Criteria andTeacherEnNmEqualTo(String value) {
            addCriterion("teacher_en_nm =", value, "teacherEnNm");
            return (Criteria) this;
        }

        public Criteria andTeacherEnNmNotEqualTo(String value) {
            addCriterion("teacher_en_nm <>", value, "teacherEnNm");
            return (Criteria) this;
        }

        public Criteria andTeacherEnNmGreaterThan(String value) {
            addCriterion("teacher_en_nm >", value, "teacherEnNm");
            return (Criteria) this;
        }

        public Criteria andTeacherEnNmGreaterThanOrEqualTo(String value) {
            addCriterion("teacher_en_nm >=", value, "teacherEnNm");
            return (Criteria) this;
        }

        public Criteria andTeacherEnNmLessThan(String value) {
            addCriterion("teacher_en_nm <", value, "teacherEnNm");
            return (Criteria) this;
        }

        public Criteria andTeacherEnNmLessThanOrEqualTo(String value) {
            addCriterion("teacher_en_nm <=", value, "teacherEnNm");
            return (Criteria) this;
        }

        public Criteria andTeacherEnNmLike(String value) {
            addCriterion("teacher_en_nm like", value, "teacherEnNm");
            return (Criteria) this;
        }

        public Criteria andTeacherEnNmNotLike(String value) {
            addCriterion("teacher_en_nm not like", value, "teacherEnNm");
            return (Criteria) this;
        }

        public Criteria andTeacherEnNmIn(List<String> values) {
            addCriterion("teacher_en_nm in", values, "teacherEnNm");
            return (Criteria) this;
        }

        public Criteria andTeacherEnNmNotIn(List<String> values) {
            addCriterion("teacher_en_nm not in", values, "teacherEnNm");
            return (Criteria) this;
        }

        public Criteria andTeacherEnNmBetween(String value1, String value2) {
            addCriterion("teacher_en_nm between", value1, value2, "teacherEnNm");
            return (Criteria) this;
        }

        public Criteria andTeacherEnNmNotBetween(String value1, String value2) {
            addCriterion("teacher_en_nm not between", value1, value2, "teacherEnNm");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(Byte value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(Byte value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(Byte value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(Byte value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(Byte value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(Byte value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<Byte> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<Byte> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(Byte value1, Byte value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(Byte value1, Byte value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andCdNumberIsNull() {
            addCriterion("cd_number is null");
            return (Criteria) this;
        }

        public Criteria andCdNumberIsNotNull() {
            addCriterion("cd_number is not null");
            return (Criteria) this;
        }

        public Criteria andCdNumberEqualTo(String value) {
            addCriterion("cd_number =", value, "cdNumber");
            return (Criteria) this;
        }

        public Criteria andCdNumberNotEqualTo(String value) {
            addCriterion("cd_number <>", value, "cdNumber");
            return (Criteria) this;
        }

        public Criteria andCdNumberGreaterThan(String value) {
            addCriterion("cd_number >", value, "cdNumber");
            return (Criteria) this;
        }

        public Criteria andCdNumberGreaterThanOrEqualTo(String value) {
            addCriterion("cd_number >=", value, "cdNumber");
            return (Criteria) this;
        }

        public Criteria andCdNumberLessThan(String value) {
            addCriterion("cd_number <", value, "cdNumber");
            return (Criteria) this;
        }

        public Criteria andCdNumberLessThanOrEqualTo(String value) {
            addCriterion("cd_number <=", value, "cdNumber");
            return (Criteria) this;
        }

        public Criteria andCdNumberLike(String value) {
            addCriterion("cd_number like", value, "cdNumber");
            return (Criteria) this;
        }

        public Criteria andCdNumberNotLike(String value) {
            addCriterion("cd_number not like", value, "cdNumber");
            return (Criteria) this;
        }

        public Criteria andCdNumberIn(List<String> values) {
            addCriterion("cd_number in", values, "cdNumber");
            return (Criteria) this;
        }

        public Criteria andCdNumberNotIn(List<String> values) {
            addCriterion("cd_number not in", values, "cdNumber");
            return (Criteria) this;
        }

        public Criteria andCdNumberBetween(String value1, String value2) {
            addCriterion("cd_number between", value1, value2, "cdNumber");
            return (Criteria) this;
        }

        public Criteria andCdNumberNotBetween(String value1, String value2) {
            addCriterion("cd_number not between", value1, value2, "cdNumber");
            return (Criteria) this;
        }

        public Criteria andCrtTimeIsNull() {
            addCriterion("crt_time is null");
            return (Criteria) this;
        }

        public Criteria andCrtTimeIsNotNull() {
            addCriterion("crt_time is not null");
            return (Criteria) this;
        }

        public Criteria andCrtTimeEqualTo(Timestamp value) {
            addCriterion("crt_time =", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotEqualTo(Timestamp value) {
            addCriterion("crt_time <>", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeGreaterThan(Timestamp value) {
            addCriterion("crt_time >", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("crt_time >=", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeLessThan(Timestamp value) {
            addCriterion("crt_time <", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("crt_time <=", value, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeIn(List<Timestamp> values) {
            addCriterion("crt_time in", values, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotIn(List<Timestamp> values) {
            addCriterion("crt_time not in", values, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("crt_time between", value1, value2, "crtTime");
            return (Criteria) this;
        }

        public Criteria andCrtTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("crt_time not between", value1, value2, "crtTime");
            return (Criteria) this;
        }

        public Criteria andModfTimeIsNull() {
            addCriterion("modf_time is null");
            return (Criteria) this;
        }

        public Criteria andModfTimeIsNotNull() {
            addCriterion("modf_time is not null");
            return (Criteria) this;
        }

        public Criteria andModfTimeEqualTo(Timestamp value) {
            addCriterion("modf_time =", value, "modfTime");
            return (Criteria) this;
        }

        public Criteria andModfTimeNotEqualTo(Timestamp value) {
            addCriterion("modf_time <>", value, "modfTime");
            return (Criteria) this;
        }

        public Criteria andModfTimeGreaterThan(Timestamp value) {
            addCriterion("modf_time >", value, "modfTime");
            return (Criteria) this;
        }

        public Criteria andModfTimeGreaterThanOrEqualTo(Timestamp value) {
            addCriterion("modf_time >=", value, "modfTime");
            return (Criteria) this;
        }

        public Criteria andModfTimeLessThan(Timestamp value) {
            addCriterion("modf_time <", value, "modfTime");
            return (Criteria) this;
        }

        public Criteria andModfTimeLessThanOrEqualTo(Timestamp value) {
            addCriterion("modf_time <=", value, "modfTime");
            return (Criteria) this;
        }

        public Criteria andModfTimeIn(List<Timestamp> values) {
            addCriterion("modf_time in", values, "modfTime");
            return (Criteria) this;
        }

        public Criteria andModfTimeNotIn(List<Timestamp> values) {
            addCriterion("modf_time not in", values, "modfTime");
            return (Criteria) this;
        }

        public Criteria andModfTimeBetween(Timestamp value1, Timestamp value2) {
            addCriterion("modf_time between", value1, value2, "modfTime");
            return (Criteria) this;
        }

        public Criteria andModfTimeNotBetween(Timestamp value1, Timestamp value2) {
            addCriterion("modf_time not between", value1, value2, "modfTime");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNull() {
            addCriterion("operator is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNotNull() {
            addCriterion("operator is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEqualTo(Long value) {
            addCriterion("operator =", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotEqualTo(Long value) {
            addCriterion("operator <>", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThan(Long value) {
            addCriterion("operator >", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThanOrEqualTo(Long value) {
            addCriterion("operator >=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThan(Long value) {
            addCriterion("operator <", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThanOrEqualTo(Long value) {
            addCriterion("operator <=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorIn(List<Long> values) {
            addCriterion("operator in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotIn(List<Long> values) {
            addCriterion("operator not in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorBetween(Long value1, Long value2) {
            addCriterion("operator between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotBetween(Long value1, Long value2) {
            addCriterion("operator not between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andRmkIsNull() {
            addCriterion("rmk is null");
            return (Criteria) this;
        }

        public Criteria andRmkIsNotNull() {
            addCriterion("rmk is not null");
            return (Criteria) this;
        }

        public Criteria andRmkEqualTo(String value) {
            addCriterion("rmk =", value, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkNotEqualTo(String value) {
            addCriterion("rmk <>", value, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkGreaterThan(String value) {
            addCriterion("rmk >", value, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkGreaterThanOrEqualTo(String value) {
            addCriterion("rmk >=", value, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkLessThan(String value) {
            addCriterion("rmk <", value, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkLessThanOrEqualTo(String value) {
            addCriterion("rmk <=", value, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkLike(String value) {
            addCriterion("rmk like", value, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkNotLike(String value) {
            addCriterion("rmk not like", value, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkIn(List<String> values) {
            addCriterion("rmk in", values, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkNotIn(List<String> values) {
            addCriterion("rmk not in", values, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkBetween(String value1, String value2) {
            addCriterion("rmk between", value1, value2, "rmk");
            return (Criteria) this;
        }

        public Criteria andRmkNotBetween(String value1, String value2) {
            addCriterion("rmk not between", value1, value2, "rmk");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_teacher
     *
     * @mbggenerated do_not_delete_during_merge Sun Aug 05 22:05:07 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_teacher
     *
     * @mbggenerated Sun Aug 05 22:05:07 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}