package com.jw.kids.bean;

import java.util.Date;

public class TTeacher {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.teacher_id
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    private Long teacherId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.teacher_nm
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    private String teacherNm;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.sex
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    private Byte sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.age
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    private Byte age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.crt_time
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    private Date crtTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.modf_time
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    private Date modfTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.operator
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    private Long operator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_teacher.rmk
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    private String rmk;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    public TTeacher(Long teacherId, String teacherNm, Byte sex, Byte age, Date crtTime, Date modfTime, Long operator, String rmk) {
        this.teacherId = teacherId;
        this.teacherNm = teacherNm;
        this.sex = sex;
        this.age = age;
        this.crtTime = crtTime;
        this.modfTime = modfTime;
        this.operator = operator;
        this.rmk = rmk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_teacher
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    public TTeacher() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.teacher_id
     *
     * @return the value of t_teacher.teacher_id
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    public Long getTeacherId() {
        return teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.teacher_id
     *
     * @param teacherId the value for t_teacher.teacher_id
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    public void setTeacherId(Long teacherId) {
        this.teacherId = teacherId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.teacher_nm
     *
     * @return the value of t_teacher.teacher_nm
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    public String getTeacherNm() {
        return teacherNm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.teacher_nm
     *
     * @param teacherNm the value for t_teacher.teacher_nm
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    public void setTeacherNm(String teacherNm) {
        this.teacherNm = teacherNm == null ? null : teacherNm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.sex
     *
     * @return the value of t_teacher.sex
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    public Byte getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.sex
     *
     * @param sex the value for t_teacher.sex
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    public void setSex(Byte sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.age
     *
     * @return the value of t_teacher.age
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    public Byte getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.age
     *
     * @param age the value for t_teacher.age
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    public void setAge(Byte age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.crt_time
     *
     * @return the value of t_teacher.crt_time
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    public Date getCrtTime() {
        return crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.crt_time
     *
     * @param crtTime the value for t_teacher.crt_time
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    public void setCrtTime(Date crtTime) {
        this.crtTime = crtTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.modf_time
     *
     * @return the value of t_teacher.modf_time
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    public Date getModfTime() {
        return modfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.modf_time
     *
     * @param modfTime the value for t_teacher.modf_time
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    public void setModfTime(Date modfTime) {
        this.modfTime = modfTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.operator
     *
     * @return the value of t_teacher.operator
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    public Long getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.operator
     *
     * @param operator the value for t_teacher.operator
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    public void setOperator(Long operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_teacher.rmk
     *
     * @return the value of t_teacher.rmk
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    public String getRmk() {
        return rmk;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_teacher.rmk
     *
     * @param rmk the value for t_teacher.rmk
     *
     * @mbggenerated Sun Jun 24 22:49:08 CST 2018
     */
    public void setRmk(String rmk) {
        this.rmk = rmk == null ? null : rmk.trim();
    }
}